[package]
name = "openpid-embedded-hal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openpid = { git = "ssh://git@github.com/dgramop/openpid" }
indoc = "2.0.4"
